[build]
  publish = "."

[[plugins]]
  package = "@netlify/plugin-sitemap"

[build.processing]
  skip_processing = true

[build]
  publish = "."
  command = ""  # No build command needed for static HTML
